---
version: '2.1'

services:
  service-auth-provider-app:
    image: hmcts/service-auth-provider-app:latest
    environment:
      - jwtKey=wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
      - microserviceKeys_em_gw=AAAAAAAAAAAAAAAA
#      logging env vars
      - JSON_CONSOLE_PRETTY_PRINT=false
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=service-auth-provider-app
      - REFORM_TEAM=rpe
      - REFORM_ENVIRONMENT=docker
#      healthcheck env vars
      - PACKAGES_ENVIRONMENT=docker
      - PACKAGES_PROJECT=rpe
      - PACKAGES_NAME=service-auth-provider-app
      - PACKAGES_VERSION=unkown
      - TESTING_SUPPORT_ENABLED=true
    ports:
      - 4502:8489

  smtp-server:
    image: mailhog/mailhog

  annotation-api-db:
    image: postgres
    restart: always
    environment:
    - POSTGRES_DB=emannotationapp
    - POSTGRES_USER=emannotationapp
    - POSTGRES_PASSWORD=emannotationapp
    ports:
    - 5444:5432
